In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Data.csv', header='infer')

X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [3]:
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [23]:
#For Handling the Missing values, the sklearn library use is sklearn.impute
from sklearn.impute import SimpleImputer

#Create instance for impute
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')

#Replacing missing values
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

In [24]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [25]:
#For encoding the Independent Variables
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
                              #[(name of encoder, encoder class(), column want to be encoded)]
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')

X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


In [26]:
#For label encoding the Dependent Variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [27]:
#Splitting the data into train and test using SKLearn
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 1)

print(X_train)
print('------------------------------')
print(X_test)
print('------------------------------')
print(y_train)
print('------------------------------')
print(y_test)
print('------------------------------')

[[1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]
------------------------------
[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]
------------------------------
[0 1 0 0 1 1 0 1]
------------------------------
[0 1]
------------------------------


In [28]:
#For Standardization of data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])

In [29]:
print(X_train[:,3:])
print(X_test)

[[1.2909944487358056 -0.19159184384578545 -1.0781259408412425]
 [-0.7745966692414834 -0.014117293757057777 -0.07013167641635372]
 [-0.7745966692414834 0.566708506533324 0.633562432710455]
 [1.2909944487358056 -0.30453019390224867 -0.30786617274297867]
 [1.2909944487358056 -1.9018011447007988 -1.420463615551582]
 [-0.7745966692414834 1.1475343068237058 1.232653363453549]
 [-0.7745966692414834 1.4379472069688968 1.5749910381638885]
 [-0.7745966692414834 -0.7401495441200351 -0.5646194287757332]]
[[1.0 0.0 1.0 -0.7745966692414834 -1.4661817944830124 -0.9069571034860727]
 [0.0 1.0 0.0 -0.7745966692414834 -0.44973664397484414 0.2056403393225306]]
